version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3101
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    depends_on:
      - backend
    networks:
      - nanjil-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3101:3101"
    environment:
      - NODE_ENV=development
      - PORT=3101
      - DATABASE_URL=${NEON_DATABASE_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CORS_ORIGINS=http://localhost:3100
    networks:
      - nanjil-network

  # Redis for caching (optional but recommended)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - nanjil-network

networks:
  nanjil-network:
    driver: bridge

volumes:
  redis_data: